title: Bennett Benedict # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:
  > # your text below (remove <br> elements if you don't need line breaks)
  Dev and Weirdo
  <br><br>
  Hey there, it's dope that you landed here. 
  <br><br>
  I am the World's Okayest Dev
  <br><br>
  <a href="https://www.linkedin.com/in/baharajr/">LinkedIn</a>

theme: jekyll-theme-leap-day
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
